#!/usr/bin/env bash
echo "--- Starting Manual Cleanup ---"
rm -rf ~/.config/ags-advanced \
~/.config/alacritty \
~/.config/anyrun \
~/.config/auto-cpufreq \
~/.config/avizo \
~/.config/bash \
~/.config/bottom \
~/.config/btop \
~/.config/cava \
~/.config/cool-retro-term \
~/.config/dolphin \
~/.config/dunst \
~/.config/eww \
~/.config/fastfetch \
~/.config/fish \
~/.config/fnott \
~/.config/fontconfig \
~/.config/foot \
~/.config/fuzzel \
~/.config/gamemode \
~/.config/gammastep \
~/.config/git \
~/.config/glava \
~/.config/gtk-3.0 \
~/.config/gtk-4.0 \
~/.config/helix \
~/.config/htop \
~/.config/hypr \
~/.config/hyprlock \
~/.config/hyprnotify \
~/.config/hyprpaper \
~/.config/ironbar \
~/.config/kanshi \
~/.config/kitty \
~/.config/kvantum \
~/.config/lutris \
~/.config/ly \
~/.config/mako \
~/.config/mangohud \
~/.config/mpv \
~/.config/nemo \
~/.config/neofetch \
~/.config/nvim \
~/.config/nwg-dock-hyprland \
~/.config/nwg-look \
~/.config/nwg-panel \
~/.config/pipewire \
~/.config/qt5ct \
~/.config/qt6ct \
~/.config/ranger \
~/.config/rofi \
~/.config/starship \
~/.config/swaybg \
~/.config/swaylock \
~/.config/swaylock-effects \
~/.config/swaync \
~/.config/swww \
~/.config/thunar \
~/.config/tlp \
~/.config/tmux \
~/.config/tofi \
~/.config/vis \
~/.config/waybar \
~/.config/wezterm \
~/.config/wireplumber \
~/.config/wlogout \
~/.config/wlsunset \
~/.config/wluma \
~/.config/wofi \
~/.config/wpaperd \
~/.config/yambar \
~/.config/yazi \
~/.config/zathura \
~/.config/zsh \
~/.config/scripts
echo "--- Manual Cleanup Complete ---"
